apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cbdtljria-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-79334aa4a6.rzmi.p3.openshiftapps.com/rhtap/rhtap-qe:644d1a2d64446c9d0a90c96c784cde38e2af2019@sha256:92dfd8bbcd9b980ef27a8eb6ecae5397da2ae367ef66fab54981f3cdd6a8e250
          name: container-image
